osx_image: xcode8.2
language: objective-c

cache:
  directories:
    - Carthage

before_install:
  - travis_wait 35; bin/bootstrap-if-needed

script:
  - xcodebuild clean build -project Imaginary.xcodeproj -scheme "Imaginary-Mac" -sdk macosx | xcpretty
  - xcodebuild clean build -project Imaginary.xcodeproj -scheme "Imaginary-iOS" -sdk iphonesimulator | xcpretty

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)

